-- MySQL Script generated by MySQL Workbench
-- Mon Jun 12 01:14:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bancoTransfer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bancoTransfer` ;

-- -----------------------------------------------------
-- Schema bancoTransfer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancoTransfer` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bancoTransfer` ;

-- -----------------------------------------------------
-- Table `bancoTransfer`.`corrida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoTransfer`.`corrida` (
  `id_pass` INT NOT NULL AUTO_INCREMENT,
  `nome_passageiro` VARCHAR(50) NOT NULL,
  `id_obs` INT NOT NULL,
  `telefone_id_telefone` INT NOT NULL,
  `end_partida` VARCHAR(45) NOT NULL,
  `end_destino` VARCHAR(45) NULL DEFAULT NULL,
  `numero_partida` VARCHAR(45) NULL DEFAULT NULL,
  `numero_destino` VARCHAR(45) NULL DEFAULT NULL,
  `ponto_ref` VARCHAR(45) NULL DEFAULT NULL,
  `email_pass` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pass`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancoTransfer`.`email_pass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoTransfer`.`email_pass` (
  `id_email` INT NOT NULL AUTO_INCREMENT,
  `email_passageiro` VARCHAR(90) NOT NULL,
  `corrida_id_pass` INT NOT NULL,
  PRIMARY KEY (`id_email`, `corrida_id_pass`),
  INDEX `fk_email_pass_corrida1_idx` (`corrida_id_pass` ASC) VISIBLE,
  CONSTRAINT `fk_email_pass_corrida1`
    FOREIGN KEY (`corrida_id_pass`)
    REFERENCES `bancoTransfer`.`corrida` (`id_pass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancoTransfer`.`forma_pag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoTransfer`.`forma_pag` (
  `id_pag` INT NOT NULL AUTO_INCREMENT,
  `fPag` VARCHAR(45) NOT NULL,
  `corrida_id_pass` INT NOT NULL,
  PRIMARY KEY (`id_pag`, `corrida_id_pass`),
  INDEX `fk_forma_pag_corrida_idx` (`corrida_id_pass` ASC) VISIBLE,
  CONSTRAINT `fk_forma_pag_corrida`
    FOREIGN KEY (`corrida_id_pass`)
    REFERENCES `bancoTransfer`.`corrida` (`id_pass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancoTransfer`.`observacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoTransfer`.`observacao` (
  `id_obs` INT NOT NULL AUTO_INCREMENT,
  `obs_texto` VARCHAR(200) NOT NULL,
  `corrida_id_pass` INT NOT NULL,
  PRIMARY KEY (`id_obs`, `corrida_id_pass`),
  INDEX `fk_observacao_corrida1_idx` (`corrida_id_pass` ASC) VISIBLE,
  CONSTRAINT `fk_observacao_corrida1`
    FOREIGN KEY (`corrida_id_pass`)
    REFERENCES `bancoTransfer`.`corrida` (`id_pass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancoTransfer`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoTransfer`.`telefone` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `tel_passageiro` VARCHAR(45) NOT NULL,
  `corrida_id_pass` INT NOT NULL,
  PRIMARY KEY (`id_telefone`, `corrida_id_pass`),
  INDEX `fk_telefone_corrida1_idx` (`corrida_id_pass` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_corrida1`
    FOREIGN KEY (`corrida_id_pass`)
    REFERENCES `bancoTransfer`.`corrida` (`id_pass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancoTransfer`.`valor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoTransfer`.`valor` (
  `id_valor` INT NOT NULL AUTO_INCREMENT,
  `valor` VARCHAR(15) NOT NULL,
  `corrida_id_pass` INT NOT NULL,
  PRIMARY KEY (`id_valor`, `corrida_id_pass`),
  INDEX `fk_valor_corrida1_idx` (`corrida_id_pass` ASC) VISIBLE,
  CONSTRAINT `fk_valor_corrida1`
    FOREIGN KEY (`corrida_id_pass`)
    REFERENCES `bancoTransfer`.`corrida` (`id_pass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancoTransfer`.`viagem_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoTransfer`.`viagem_data` (
  `id_data` INT NOT NULL AUTO_INCREMENT,
  `v_data` DATE NOT NULL,
  PRIMARY KEY (`id_data`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancoTransfer`.`viagem_data_has_corrida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoTransfer`.`viagem_data_has_corrida` (
  `viagem_data_id_data` INT NOT NULL,
  `corrida_id_pass` INT NOT NULL,
  PRIMARY KEY (`viagem_data_id_data`, `corrida_id_pass`),
  INDEX `fk_viagem_data_has_corrida_corrida1_idx` (`corrida_id_pass` ASC) VISIBLE,
  INDEX `fk_viagem_data_has_corrida_viagem_data1_idx` (`viagem_data_id_data` ASC) VISIBLE,
  CONSTRAINT `fk_viagem_data_has_corrida_viagem_data1`
    FOREIGN KEY (`viagem_data_id_data`)
    REFERENCES `bancoTransfer`.`viagem_data` (`id_data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_data_has_corrida_corrida1`
    FOREIGN KEY (`corrida_id_pass`)
    REFERENCES `bancoTransfer`.`corrida` (`id_pass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
